sudo: enabled
dist: xenial
language: go
go:
  - "1.10"

before_install:
  - "sudo apt-get install go-bindata"
  - 'go-bindata -o="cmd/magneticow/bindata.go" -prefix="cmd/magneticow/data/" cmd/magneticow/data/...'

install:
  - "go get --tags fts5 -t ./..."

script:
  - go test ./cmd/... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)