sudo: enabled
dist: xenial
language: go
go:
  - 1.8.3

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install python3-dev"
  - "pip3 install mypy pylint"

  - ""

install:
  - "pip3 install ./magneticod"
  - "pip3 install ./magneticow"

script:
  - "pylint ./magneticod/magneticod"
  - "pylint ./magneticow/magneticow"
  - "mypy --ignore-missing-imports --follow-imports=skip ./magneticod/magneticod"
  - "mypy --ignore-missing-imports --follow-imports=skip ./magneticow/magneticow"