sudo: enabled
dist: xenial
language: go
go:
  - 1.10
  - tip

before_install:
  - "sudo apt-get install go-bindata"

install:
  - "go get -t fts5 ./..."

script:
  - make all
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)