version: "2"

volumes:
  shared_db:

services:
  magneticod:
    build:
      context: magneticod
    volumes:
      - shared_db:/root/.local/share
    ports:
      - "6881:6881"
      - "6881:6881/udp"

  magneticow:
    build:
      context: magneticow
    volumes:
      - shared_db:/root/.local/share

    ports:
      - "8080:8080"
